#!/bin/sh
# Start/Stop daemon

# --- project name
DAEMON=dmtpd
DAEMON_ARGS=

# --- start/stop script
. /etc/init.d/daemon.sh

# --- command line options
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
exit $?
