
// ----------------------------------------------------------------------------
// This file is included directly into 'propman.c' at compile time, it cannot
// be compiled on it's own.

  //  KeyCode                      Name               Type           Attr     Ndx  Init
  //{ PROP_CUST_GEOFENCE_1       , "cst.geof.1"     , KVT_GPS      , SAVE    ,  1,  "" },
  //{ PROP_CUST_GEOFENCE_2       , "cst.geof.2"     , KVT_GPS      , SAVE    ,  1,  "" },
  //{ PROP_CUST_GEOFENCE_3       , "cst.geof.3"     , KVT_GPS      , SAVE    ,  1,  "" },
  //{ PROP_CUST_GEOFENCE_4       , "cst.geof.4"     , KVT_GPS      , SAVE    ,  1,  "" },

// ----------------------------------------------------------------------------
